"""Add auth and teams tables: refresh_tokens, ws_tickets, node_teams; drop nodes.team_id

Revision ID: 0003
Revises: 0002
Create Date: 2026-03-21
"""

from alembic import op
import sqlalchemy as sa

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Create refresh_tokens table
    op.create_table(
        "refresh_tokens",
        sa.Column("token_id", sa.String(36), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("token_hash", sa.String(255), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"]),
        sa.PrimaryKeyConstraint("token_id"),
    )
    op.create_index(
        "ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False
    )

    # 2. Create ws_tickets table
    op.create_table(
        "ws_tickets",
        sa.Column("ticket_id", sa.String(36), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"]),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    op.create_index(
        "ix_ws_tickets_user_id", "ws_tickets", ["user_id"], unique=False
    )

    # 3. Create node_teams junction table (replaces nodes.team_id)
    op.create_table(
        "node_teams",
        sa.Column("node_id", sa.String(255), nullable=False),
        sa.Column("team_id", sa.String(36), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.node_id"]),
        sa.ForeignKeyConstraint(["team_id"], ["teams.team_id"]),
        sa.PrimaryKeyConstraint("node_id", "team_id"),
    )

    # 4. Migrate existing node->team assignments to junction table
    op.execute(
        sa.text(
            "INSERT INTO node_teams (node_id, team_id, assigned_at) "
            "SELECT node_id, team_id, first_seen FROM nodes WHERE team_id IS NOT NULL"
        )
    )

    # 5. Drop nodes.team_id FK constraint then column
    # Constraint name auto-generated by PostgreSQL from migration 0001
    op.drop_constraint("nodes_team_id_fkey", "nodes", type_="foreignkey")
    op.drop_column("nodes", "team_id")


def downgrade() -> None:
    # 1. Re-add team_id column to nodes
    op.add_column(
        "nodes",
        sa.Column("team_id", sa.String(36), nullable=True),
    )
    op.create_foreign_key(
        "nodes_team_id_fkey", "nodes", "teams", ["team_id"], ["team_id"]
    )

    # 2. Restore node->team assignments (last assignment wins if multiple)
    op.execute(
        sa.text(
            "UPDATE nodes SET team_id = nt.team_id "
            "FROM ("
            "  SELECT DISTINCT ON (node_id) node_id, team_id "
            "  FROM node_teams "
            "  ORDER BY node_id, assigned_at DESC"
            ") nt WHERE nodes.node_id = nt.node_id"
        )
    )

    # 3. Drop node_teams
    op.drop_table("node_teams")

    # 4. Drop ws_tickets
    op.drop_index("ix_ws_tickets_user_id", table_name="ws_tickets")
    op.drop_table("ws_tickets")

    # 5. Drop refresh_tokens
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
